apiVersion: apps/v1
kind: Deployment
metadata:
  name: gic-plateforme-deployment
  labels:
    app: gic-plateforme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gic-plateforme
  template:
    metadata:
      labels:
        app: gic-plateforme
    spec:
      containers:
      - name: gic-plateforme-container
        image: david5831/gic-plateforme:c9627d0a922668bdb6be6f682997669f3b71381c
        ports:
        - containerPort: 8000
        command: ["python"]
        args: ["manage.py", "runserver", "0.0.0.0:8000"]
      
          # C'est ici que la magie opère 🪄
        envFrom:
          - configMapRef:
              name: gic-plateforme-config
          - secretRef:
              name: gic-plateforme-secret