apiVersion: v1
kind: Secret
metadata:
  name: gic-plateforme-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-y&)oge8+u$41if)6v=g*=dpi6_k)&xuzz1fd+h0q=(l2q1-vhm"  
  EMAIL_HOST_USER: 'contactgic239@gmail.com'
  EMAIL_HOST_PASSWORD: 'csmytecmobqpavkr'  