apiVersion: v1
kind: Service
metadata:
  name: gic-plateforme-service
  namespace: default
spec:
  selector:
    app: gic-plateforme
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
